name: Deploy PHP App to Azure using GitHub Actions

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AZURE_RESOURCE_GROUP: riadresources
      AZURE_WEBAPP_NAME: riad-app

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install Composer dependencies
      run: composer install --no-progress --prefer-dist

    - name: Archive project files
      run: zip -r riad-myphpapp.zip .

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      run: |
        az webapp deployment source config-zip \
          --resource-group $AZURE_RESOURCE_GROUP \
          --name $AZURE_WEBAPP_NAME \
          --src riad-myphpapp.zip
